extends:
  - next/core-web-vitals
  - prettier
  - plugin:import/recommended
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  "@next/next/no-img-element": off
  import/order:
    - error
    - newlines-between: always
      pathGroups:
        - pattern: "@local/**"
          group: external
          position: after
settings:
  import/resolver:
    alias:
      map:
        - - "@local"
          - "./src"
      extensions:
        - ".ts"
        - ".js"
        - ".jsx"
        - ".json"
    node:
      paths:
        - "./src"
