name: Publish corgi cli
on:
  push:
    branches:
      - main
    paths:
      - "cli/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Publish to NPM registry
      # Setup .npmrc file on the fly
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        working-directory: "./cli"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}